[package]
name = "rust-sandbox"
version = "0.1.0"
authors = ["kgill"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libraw-rs = "0.0.4"
image = "0.23.14"
